spring.application.name=Acutator-Demo
server.port=8020
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.info.env.enabled=true
info.app.name=Acutator-Demo
info.app.version=1.0.0
info.app.description=This is a demo application to showcase Spring Boot Actuator features.
