spring.application.name=APIGateway

server.port=8013
spring.cloud.gateway.server.webmvc.routes[0].id=Product
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8011
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/products/**

spring.cloud.gateway.server.webmvc.routes[1].id=CartService
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8012
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/carts/**


