spring.application.name=CartService

server.port=8012

eureka.client.service-url.defaultZone=http://localhost:8855/eureka

# Register this service with Eureka
eureka.client.register-with-eureka=true

# Fetch the registry of other services
eureka.client.fetch-registry=true